# -*- coding: utf-8 -*-
"""AvailabilityMatrix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ExuNezHslASwVEUElvdH8S9aBHht0CBr
"""


import pandas as pd
import openpyxl
import io

from google.colab import files
uploaded = files.upload()

print(uploaded.keys())

df = pd.read_excel(io.BytesIO(uploaded['TestStudentAvailability.xlsx']))

df.info()
df = df.drop('__PowerAppsId__',axis=1)

df.head()

"""###Define Shifts based off of excel file"""

shifts = [
  ("Mon", 7.25, 9), ("Mon", 9, 12), ("Mon", 12, 15), ("Mon", 15, 17), ("Mon", 17, 19),
  ("Tue", 7.25, 9), ("Tue", 9, 12), ("Tue", 12, 15), ("Tue", 15, 17), ("Tue", 17, 19),
  ("Wed", 7.25, 9), ("Wed", 9, 12), ("Wed", 12, 15), ("Wed", 15, 17), ("Wed", 17, 19),
  ("Thu", 7.25, 9), ("Thu", 9, 12), ("Thu", 12, 15), ("Thu", 15, 17), ("Thu", 17, 19),
  ("Fri", 7.25, 9), ("Fri", 9, 12), ("Fri", 12, 15), ("Fri", 15, 17),
 ("Sat", 10, 14),
  ("Sun", 10, 14)
]

import ast
from datetime import datetime

def time_str_to_float(t):
    """Converts 'HH:MM:SS' to float hour (e.g., 07:15:00 → 7.25)"""
    dt = datetime.strptime(t.strip(), "%H:%M:%S")
    return dt.hour + dt.minute / 60

availability_matrix = {}

for student_index, row in df.iterrows():
    student_name = row["STUDENT NAME"].strip().title()
    availability_matrix[student_name] = {}

    for (day_abbr, start, end) in shifts:
        full_day = {
            "Mon": "MONDAY", "Tue": "TUESDAY", "Wed": "WEDNESDAY",
            "Thu": "THURSDAY", "Fri": "FRIDAY", "Sat": "SATURDAY", "Sun": "SUNDAY"
        }[day_abbr]

        raw = row.get(full_day)
        time_ranges = []

        if isinstance(raw, str):
            try:
                time_ranges = ast.literal_eval(raw)
            except Exception as e:
                print(f"⚠️ Failed to parse {student_name} {full_day}: {e}")
                time_ranges = []

        # Parse ranges into float tuples
        parsed_ranges = []
        for rng in time_ranges:
            try:
                start_str, end_str = rng.split("-")
                rng_start = time_str_to_float(start_str)
                rng_end = time_str_to_float(end_str)
                parsed_ranges.append((rng_start, rng_end))
            except:
                continue

        # Check if shift fits entirely within any range
        is_available = any(rng_start <= start and end <= rng_end for (rng_start, rng_end) in parsed_ranges)
        availability_matrix[student_name][(day_abbr, start, end)] = int(is_available)

print(availability_matrix)