# -*- coding: utf-8 -*-
"""AvailabilityMatrix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ExuNezHslASwVEUElvdH8S9aBHht0CBr
"""



import pandas as pd
import openpyxl
import io

from google.colab import files
uploaded = files.upload()

print(uploaded.keys())

df = pd.read_excel(io.BytesIO(uploaded['TestStudentAvailability.xlsx']))

df.info()
df = df.drop('__PowerAppsId__',axis=1)

df.head()

"""###Define Shifts based off of excel file"""

shifts = [
    ("S1",  "Mon", 7.25, 9,  3),
    ("S2",  "Mon", 9,    12, 4),
    ("S3",  "Mon", 12,   15, 4),
    ("S4",  "Mon", 15,   17, 4),
    ("S5",  "Mon", 17,   19, 3),

    ("S6",  "Tue", 7.25, 9,  3),
    ("S7",  "Tue", 9,    12, 4),
    ("S8",  "Tue", 12,   15, 4),
    ("S9",  "Tue", 15,   17, 4),
    ("S10", "Tue", 17,   19, 3),

    ("S11", "Wed", 7.25, 9,  3),
    ("S12", "Wed", 9,    12, 4),
    ("S13", "Wed", 12,   15, 4),
    ("S14", "Wed", 15,   17, 4),
    ("S15", "Wed", 17,   19, 3),

    ("S16", "Thu", 7.25, 9,  3),
    ("S17", "Thu", 9,    12, 4),
    ("S18", "Thu", 12,   15, 4),
    ("S19", "Thu", 15,   17, 4),
    ("S20", "Thu", 17,   19, 3),

    ("S21", "Fri", 7.25, 9,  3),
    ("S22", "Fri", 9,    12, 4),
    ("S23", "Fri", 12,   15, 4),
    ("S24", "Fri", 15,   17, 4),

    ("S25", "Sat", 10,   14, 2),
    ("S26", "Sun", 10,   14, 2),
]


import ast
from datetime import datetime

def time_str_to_float(t):
    """Converts 'HH:MM:SS' to float hour (e.g., 07:15:00 → 7.25)"""
    dt = datetime.strptime(t.strip(), "%H:%M:%S")
    return dt.hour + dt.minute / 60

availability_matrix = {}

for student_index, row in df.iterrows():
    student_name = row["STUDENT NAME"].strip().title()
    availability_matrix[student_name] = {}

    for (day_abbr, start, end) in shifts:
        full_day = {
            "Mon": "MONDAY", "Tue": "TUESDAY", "Wed": "WEDNESDAY",
            "Thu": "THURSDAY", "Fri": "FRIDAY", "Sat": "SATURDAY", "Sun": "SUNDAY"
        }[day_abbr]

        raw = row.get(full_day)
        time_ranges = []

        if isinstance(raw, str):
            try:
                time_ranges = ast.literal_eval(raw)
            except Exception as e:
                print(f"⚠️ Failed to parse {student_name} {full_day}: {e}")
                time_ranges = []

        # Parse ranges into float tuples
        parsed_ranges = []
        for rng in time_ranges:
            try:
                start_str, end_str = rng.split("-")
                rng_start = time_str_to_float(start_str)
                rng_end = time_str_to_float(end_str)
                parsed_ranges.append((rng_start, rng_end))
            except:
                continue

        # Check if shift fits entirely within any range
        is_available = any(rng_start <= start and end <= rng_end for (rng_start, rng_end) in parsed_ranges)
        availability_matrix[student_name][(day_abbr, start, end)] = int(is_available)

print(availability_matrix)