# -*- coding: utf-8 -*-
"""SchedulingTest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M0oayAhagFn6GMTR6Q-9LUDwdLTwpd9q

#Scheduling test using example students
##Install Dependencies
"""


from ortools.sat.python import cp_model

"""#The student data"""

students = ['Emily Rivera', 'Marcus Chen', 'Sophia Johnson', 'Noah Patel', 'Isabella Brown', 'Ethan Davis', 'Ava Wilson', 'Liam Garcia', 'Olivia Lee', 'Lucas Martinez', 'Mia Anderson', 'James Thomas', 'Charlotte Taylor', 'Benjamin White', 'Amelia Harris', 'Elijah Clark', 'Harper Lewis', 'Henry Walker', 'Evelyn Hall', 'Alexander Young']

availability_matrix = {'Emily Rivera': {('Mon', 7.25, 9): 1, ('Mon', 9, 12): 1, ('Mon', 12, 15): 1, ('Mon', 15, 17): 1, ('Mon', 17, 19): 1, ('Tue', 7.25, 9): 1, ('Tue', 9, 12): 1, ('Tue', 12, 15): 1, ('Tue', 15, 17): 1, ('Tue', 17, 19): 1, ('Wed', 7.25, 9): 1, ('Wed', 9, 12): 1, ('Wed', 12, 15): 1, ('Wed', 15, 17): 1, ('Wed', 17, 19): 1, ('Thu', 7.25, 9): 1, ('Thu', 9, 12): 1, ('Thu', 12, 15): 1, ('Thu', 15, 17): 1, ('Thu', 17, 19): 1, ('Fri', 7.25, 9): 1, ('Fri', 9, 12): 1, ('Fri', 12, 15): 1, ('Fri', 15, 17): 1, ('Sat', 10, 14): 1, ('Sun', 10, 14): 1},
                       'Marcus Chen': {('Mon', 7.25, 9): 0, ('Mon', 9, 12): 0, ('Mon', 12, 15): 1, ('Mon', 15, 17): 0, ('Mon', 17, 19): 1, ('Tue', 7.25, 9): 0, ('Tue', 9, 12): 0, ('Tue', 12, 15): 0, ('Tue', 15, 17): 0, ('Tue', 17, 19): 0, ('Wed', 7.25, 9): 0, ('Wed', 9, 12): 1, ('Wed', 12, 15): 1, ('Wed', 15, 17): 0, ('Wed', 17, 19): 1, ('Thu', 7.25, 9): 1, ('Thu', 9, 12): 1, ('Thu', 12, 15): 0, ('Thu', 15, 17): 0, ('Thu', 17, 19): 0, ('Fri', 7.25, 9): 1, ('Fri', 9, 12): 0, ('Fri', 12, 15): 1, ('Fri', 15, 17): 1, ('Sat', 10, 14): 0, ('Sun', 10, 14): 0},
                       'Sophia Johnson': {('Mon', 7.25, 9): 0, ('Mon', 9, 12): 0, ('Mon', 12, 15): 0, ('Mon', 15, 17): 0, ('Mon', 17, 19): 0, ('Tue', 7.25, 9): 0, ('Tue', 9, 12): 0, ('Tue', 12, 15): 1, ('Tue', 15, 17): 1, ('Tue', 17, 19): 0, ('Wed', 7.25, 9): 1, ('Wed', 9, 12): 1, ('Wed', 12, 15): 0, ('Wed', 15, 17): 0, ('Wed', 17, 19): 1, ('Thu', 7.25, 9): 0, ('Thu', 9, 12): 0, ('Thu', 12, 15): 0, ('Thu', 15, 17): 0, ('Thu', 17, 19): 1, ('Fri', 7.25, 9): 0, ('Fri', 9, 12): 1, ('Fri', 12, 15): 1, ('Fri', 15, 17): 0, ('Sat', 10, 14): 1, ('Sun', 10, 14): 1},
                       'Noah Patel': {('Mon', 7.25, 9): 0, ('Mon', 9, 12): 1, ('Mon', 12, 15): 0, ('Mon', 15, 17): 1, ('Mon', 17, 19): 0, ('Tue', 7.25, 9): 0, ('Tue', 9, 12): 1, ('Tue', 12, 15): 1, ('Tue', 15, 17): 0, ('Tue', 17, 19): 1, ('Wed', 7.25, 9): 0, ('Wed', 9, 12): 0, ('Wed', 12, 15): 0, ('Wed', 15, 17): 0, ('Wed', 17, 19): 0, ('Thu', 7.25, 9): 1, ('Thu', 9, 12): 0, ('Thu', 12, 15): 1, ('Thu', 15, 17): 0, ('Thu', 17, 19): 0, ('Fri', 7.25, 9): 1, ('Fri', 9, 12): 0, ('Fri', 12, 15): 0, ('Fri', 15, 17): 1, ('Sat', 10, 14): 1, ('Sun', 10, 14): 0},
                       'Isabella Brown': {('Mon', 7.25, 9): 1, ('Mon', 9, 12): 0, ('Mon', 12, 15): 1, ('Mon', 15, 17): 0, ('Mon', 17, 19): 0, ('Tue', 7.25, 9): 0, ('Tue', 9, 12): 1, ('Tue', 12, 15): 0, ('Tue', 15, 17): 0, ('Tue', 17, 19): 0, ('Wed', 7.25, 9): 0, ('Wed', 9, 12): 1, ('Wed', 12, 15): 1, ('Wed', 15, 17): 1, ('Wed', 17, 19): 1, ('Thu', 7.25, 9): 0, ('Thu', 9, 12): 1, ('Thu', 12, 15): 0, ('Thu', 15, 17): 0, ('Thu', 17, 19): 1, ('Fri', 7.25, 9): 0, ('Fri', 9, 12): 1, ('Fri', 12, 15): 0, ('Fri', 15, 17): 1, ('Sat', 10, 14): 1, ('Sun', 10, 14): 1},
                       'Ethan Davis': {('Mon', 7.25, 9): 0, ('Mon', 9, 12): 0, ('Mon', 12, 15): 0, ('Mon', 15, 17): 0, ('Mon', 17, 19): 0, ('Tue', 7.25, 9): 1, ('Tue', 9, 12): 0, ('Tue', 12, 15): 1, ('Tue', 15, 17): 0, ('Tue', 17, 19): 0, ('Wed', 7.25, 9): 0, ('Wed', 9, 12): 1, ('Wed', 12, 15): 1, ('Wed', 15, 17): 0, ('Wed', 17, 19): 0, ('Thu', 7.25, 9): 1, ('Thu', 9, 12): 1, ('Thu', 12, 15): 1, ('Thu', 15, 17): 1, ('Thu', 17, 19): 1, ('Fri', 7.25, 9): 0, ('Fri', 9, 12): 1, ('Fri', 12, 15): 1, ('Fri', 15, 17): 1, ('Sat', 10, 14): 1, ('Sun', 10, 14): 1},
                       'Ava Wilson': {('Mon', 7.25, 9): 0, ('Mon', 9, 12): 1, ('Mon', 12, 15): 0, ('Mon', 15, 17): 1, ('Mon', 17, 19): 1, ('Tue', 7.25, 9): 1, ('Tue', 9, 12): 1, ('Tue', 12, 15): 0, ('Tue', 15, 17): 1, ('Tue', 17, 19): 0, ('Wed', 7.25, 9): 1, ('Wed', 9, 12): 0, ('Wed', 12, 15): 0, ('Wed', 15, 17): 0, ('Wed', 17, 19): 1, ('Thu', 7.25, 9): 0, ('Thu', 9, 12): 0, ('Thu', 12, 15): 1, ('Thu', 15, 17): 0, ('Thu', 17, 19): 0, ('Fri', 7.25, 9): 1, ('Fri', 9, 12): 0, ('Fri', 12, 15): 0, ('Fri', 15, 17): 1,  ('Sat', 10, 14): 1, ('Sun', 10, 14): 1},
                       'Liam Garcia': {('Mon', 7.25, 9): 0, ('Mon', 9, 12): 0, ('Mon', 12, 15): 1, ('Mon', 15, 17): 1, ('Mon', 17, 19): 0, ('Tue', 7.25, 9): 0, ('Tue', 9, 12): 0, ('Tue', 12, 15): 0, ('Tue', 15, 17): 0, ('Tue', 17, 19): 0, ('Wed', 7.25, 9): 0, ('Wed', 9, 12): 1, ('Wed', 12, 15): 1, ('Wed', 15, 17): 0, ('Wed', 17, 19): 0, ('Thu', 7.25, 9): 0, ('Thu', 9, 12): 0, ('Thu', 12, 15): 0, ('Thu', 15, 17): 0, ('Thu', 17, 19): 1, ('Fri', 7.25, 9): 0, ('Fri', 9, 12): 1, ('Fri', 12, 15): 1, ('Fri', 15, 17): 1,  ('Sat', 10, 14): 1, ('Sun', 10, 14): 1},
                       'Olivia Lee': {('Mon', 7.25, 9): 0, ('Mon', 9, 12): 1, ('Mon', 12, 15): 0, ('Mon', 15, 17): 0, ('Mon', 17, 19): 1, ('Tue', 7.25, 9): 0, ('Tue', 9, 12): 0, ('Tue', 12, 15): 0, ('Tue', 15, 17): 0, ('Tue', 17, 19): 0, ('Wed', 7.25, 9): 1, ('Wed', 9, 12): 0, ('Wed', 12, 15): 0, ('Wed', 15, 17): 1, ('Wed', 17, 19): 0, ('Thu', 7.25, 9): 1, ('Thu', 9, 12): 0, ('Thu', 12, 15): 1, ('Thu', 15, 17): 1, ('Thu', 17, 19): 0, ('Fri', 7.25, 9): 1, ('Fri', 9, 12): 0, ('Fri', 12, 15): 0, ('Fri', 15, 17): 0,  ('Sat', 10, 14): 0, ('Sun', 10, 14): 1},
                       'Lucas Martinez': {('Mon', 7.25, 9): 1, ('Mon', 9, 12): 0, ('Mon', 12, 15): 1, ('Mon', 15, 17): 0, ('Mon', 17, 19): 1, ('Tue', 7.25, 9): 0, ('Tue', 9, 12): 0, ('Tue', 12, 15): 1, ('Tue', 15, 17): 1, ('Tue', 17, 19): 0, ('Wed', 7.25, 9): 0, ('Wed', 9, 12): 1, ('Wed', 12, 15): 1, ('Wed', 15, 17): 0, ('Wed', 17, 19): 0, ('Thu', 7.25, 9): 1, ('Thu', 9, 12): 1, ('Thu', 12, 15): 0, ('Thu', 15, 17): 1, ('Thu', 17, 19): 0, ('Fri', 7.25, 9): 0, ('Fri', 9, 12): 0, ('Fri', 12, 15): 1, ('Fri', 15, 17): 0, ('Sat', 10, 14): 1, ('Sun', 10, 14): 1},
                       'Mia Anderson': {('Mon', 7.25, 9): 1, ('Mon', 9, 12): 0, ('Mon', 12, 15): 0, ('Mon', 15, 17): 0, ('Mon', 17, 19): 0, ('Tue', 7.25, 9): 1, ('Tue', 9, 12): 1, ('Tue', 12, 15): 0, ('Tue', 15, 17): 0, ('Tue', 17, 19): 1, ('Wed', 7.25, 9): 1, ('Wed', 9, 12): 0, ('Wed', 12, 15): 0, ('Wed', 15, 17): 0, ('Wed', 17, 19): 0, ('Thu', 7.25, 9): 0, ('Thu', 9, 12): 0, ('Thu', 12, 15): 1, ('Thu', 15, 17): 0, ('Thu', 17, 19): 1, ('Fri', 7.25, 9): 1, ('Fri', 9, 12): 1, ('Fri', 12, 15): 0, ('Fri', 15, 17): 1, ('Sat', 10, 14): 1,('Sun', 10, 14): 1},
                       'James Thomas': {('Mon', 7.25, 9): 0, ('Mon', 9, 12): 0, ('Mon', 12, 15): 0, ('Mon', 15, 17): 0, ('Mon', 17, 19): 0, ('Tue', 7.25, 9): 0, ('Tue', 9, 12): 0, ('Tue', 12, 15): 1, ('Tue', 15, 17): 1, ('Tue', 17, 19): 0, ('Wed', 7.25, 9): 0, ('Wed', 9, 12): 0, ('Wed', 12, 15): 1, ('Wed', 15, 17): 1, ('Wed', 17, 19): 0, ('Thu', 7.25, 9): 0, ('Thu', 9, 12): 0, ('Thu', 12, 15): 0, ('Thu', 15, 17): 0, ('Thu', 17, 19): 0, ('Fri', 7.25, 9): 0, ('Fri', 9, 12): 1, ('Fri', 12, 15): 1, ('Fri', 15, 17): 1,  ('Sat', 10, 14): 0,  ('Sun', 10, 14): 1},
                       'Charlotte Taylor': {('Mon', 7.25, 9): 0, ('Mon', 9, 12): 0, ('Mon', 12, 15): 0, ('Mon', 15, 17): 1, ('Mon', 17, 19): 1, ('Tue', 7.25, 9): 0, ('Tue', 9, 12): 1, ('Tue', 12, 15): 0, ('Tue', 15, 17): 0, ('Tue', 17, 19): 0, ('Wed', 7.25, 9): 0, ('Wed', 9, 12): 0, ('Wed', 12, 15): 1, ('Wed', 15, 17): 0, ('Wed', 17, 19): 1, ('Thu', 7.25, 9): 0, ('Thu', 9, 12): 0, ('Thu', 12, 15): 0, ('Thu', 15, 17): 0, ('Thu', 17, 19): 1, ('Fri', 7.25, 9): 0, ('Fri', 9, 12): 1, ('Fri', 12, 15): 1, ('Fri', 15, 17): 1, ('Sat', 10, 14): 0, ('Sun', 10, 14): 1},
                       'Benjamin White': {('Mon', 7.25, 9): 0, ('Mon', 9, 12): 0, ('Mon', 12, 15): 1, ('Mon', 15, 17): 0, ('Mon', 17, 19): 0, ('Tue', 7.25, 9): 1, ('Tue', 9, 12): 0, ('Tue', 12, 15): 1, ('Tue', 15, 17): 0, ('Tue', 17, 19): 0, ('Wed', 7.25, 9): 1, ('Wed', 9, 12): 0, ('Wed', 12, 15): 0, ('Wed', 15, 17): 0, ('Wed', 17, 19): 0, ('Thu', 7.25, 9): 1, ('Thu', 9, 12): 0, ('Thu', 12, 15): 1, ('Thu', 15, 17): 1, ('Thu', 17, 19): 0, ('Fri', 7.25, 9): 1, ('Fri', 9, 12): 0, ('Fri', 12, 15): 0, ('Fri', 15, 17): 0, ('Sat', 10, 14): 1, ('Sun', 10, 14): 1},
                       'Amelia Harris': {('Mon', 7.25, 9): 0, ('Mon', 9, 12): 0, ('Mon', 12, 15): 0, ('Mon', 15, 17): 0, ('Mon', 17, 19): 1, ('Tue', 7.25, 9): 0, ('Tue', 9, 12): 0, ('Tue', 12, 15): 0, ('Tue', 15, 17): 1, ('Tue', 17, 19): 0, ('Wed', 7.25, 9): 0, ('Wed', 9, 12): 1, ('Wed', 12, 15): 0, ('Wed', 15, 17): 1, ('Wed', 17, 19): 0, ('Thu', 7.25, 9): 0, ('Thu', 9, 12): 1, ('Thu', 12, 15): 0, ('Thu', 15, 17): 1, ('Thu', 17, 19): 1, ('Fri', 7.25, 9): 1, ('Fri', 9, 12): 1, ('Fri', 12, 15): 1, ('Fri', 15, 17): 1, ('Sat', 10, 14): 0,('Sun', 10, 14): 1},
                       'Elijah Clark': {('Mon', 7.25, 9): 1, ('Mon', 9, 12): 1, ('Mon', 12, 15): 1, ('Mon', 15, 17): 1, ('Mon', 17, 19): 0, ('Tue', 7.25, 9): 0, ('Tue', 9, 12): 1, ('Tue', 12, 15): 1, ('Tue', 15, 17): 0, ('Tue', 17, 19): 1, ('Wed', 7.25, 9): 1, ('Wed', 9, 12): 1, ('Wed', 12, 15): 0, ('Wed', 15, 17): 1, ('Wed', 17, 19): 0, ('Thu', 7.25, 9): 1, ('Thu', 9, 12): 0, ('Thu', 12, 15): 1, ('Thu', 15, 17): 1, ('Thu', 17, 19): 0, ('Fri', 7.25, 9): 1, ('Fri', 9, 12): 0, ('Fri', 12, 15): 1, ('Fri', 15, 17): 1, ('Sat', 10, 14): 1, ('Sun', 10, 14): 0},
                       'Harper Lewis': {('Mon', 7.25, 9): 0, ('Mon', 9, 12): 0, ('Mon', 12, 15): 0, ('Mon', 15, 17): 1, ('Mon', 17, 19): 1, ('Tue', 7.25, 9): 1, ('Tue', 9, 12): 0, ('Tue', 12, 15): 0, ('Tue', 15, 17): 1, ('Tue', 17, 19): 0, ('Wed', 7.25, 9): 0, ('Wed', 9, 12): 0, ('Wed', 12, 15): 0, ('Wed', 15, 17): 0, ('Wed', 17, 19): 1, ('Thu', 7.25, 9): 0, ('Thu', 9, 12): 1, ('Thu', 12, 15): 0, ('Thu', 15, 17): 0, ('Thu', 17, 19): 0, ('Fri', 7.25, 9): 0, ('Fri', 9, 12): 1, ('Fri', 12, 15): 0, ('Fri', 15, 17): 0, ('Sat', 10, 14): 0, ('Sun', 10, 14): 1},
                       'Henry Walker': {('Mon', 7.25, 9): 0, ('Mon', 9, 12): 1, ('Mon', 12, 15): 1, ('Mon', 15, 17): 0, ('Mon', 17, 19): 0, ('Tue', 7.25, 9): 0, ('Tue', 9, 12): 0, ('Tue', 12, 15): 1, ('Tue', 15, 17): 1, ('Tue', 17, 19): 0, ('Wed', 7.25, 9): 1, ('Wed', 9, 12): 0, ('Wed', 12, 15): 0, ('Wed', 15, 17): 0, ('Wed', 17, 19): 1, ('Thu', 7.25, 9): 0, ('Thu', 9, 12): 0, ('Thu', 12, 15): 0, ('Thu', 15, 17): 1, ('Thu', 17, 19): 1, ('Fri', 7.25, 9): 0, ('Fri', 9, 12): 0, ('Fri', 12, 15): 0, ('Fri', 15, 17): 1, ('Sat', 10, 14): 1, ('Sun', 10, 14): 1},
                       'Evelyn Hall': {('Mon', 7.25, 9): 1, ('Mon', 9, 12): 0, ('Mon', 12, 15): 1, ('Mon', 15, 17): 0, ('Mon', 17, 19): 1, ('Tue', 7.25, 9): 0, ('Tue', 9, 12): 1, ('Tue', 12, 15): 0, ('Tue', 15, 17): 0, ('Tue', 17, 19): 1, ('Wed', 7.25, 9): 0, ('Wed', 9, 12): 1, ('Wed', 12, 15): 0, ('Wed', 15, 17): 0, ('Wed', 17, 19): 0, ('Thu', 7.25, 9): 0, ('Thu', 9, 12): 1, ('Thu', 12, 15): 1, ('Thu', 15, 17): 0, ('Thu', 17, 19): 0, ('Fri', 7.25, 9): 0, ('Fri', 9, 12): 1, ('Fri', 12, 15): 0, ('Fri', 15, 17): 0,('Sat', 10, 14): 0, ('Sun', 10, 14): 1},
                       'Alexander Young': {('Mon', 7.25, 9): 0, ('Mon', 9, 12): 1, ('Mon', 12, 15): 0, ('Mon', 15, 17): 0, ('Mon', 17, 19): 0, ('Tue', 7.25, 9): 0, ('Tue', 9, 12): 0, ('Tue', 12, 15): 1, ('Tue', 15, 17): 0, ('Tue', 17, 19): 0, ('Wed', 7.25, 9): 1, ('Wed', 9, 12): 0, ('Wed', 12, 15): 0, ('Wed', 15, 17): 1, ('Wed', 17, 19): 1, ('Thu', 7.25, 9): 0, ('Thu', 9, 12): 1, ('Thu', 12, 15): 0, ('Thu', 15, 17): 0, ('Thu', 17, 19): 0, ('Fri', 7.25, 9): 0, ('Fri', 9, 12): 1, ('Fri', 12, 15): 1, ('Fri', 15, 17): 1,  ('Sat', 10, 14): 1, ('Sun', 10, 14): 1}}

"""##Define the shifts"""

shifts = [
    ("S1",  "Mon", 7.25, 9,  3),
    ("S2",  "Mon", 9,    12, 4),
    ("S3",  "Mon", 12,   15, 4),
    ("S4",  "Mon", 15,   17, 4),
    ("S5",  "Mon", 17,   19, 3),

    ("S6",  "Tue", 7.25, 9,  3),
    ("S7",  "Tue", 9,    12, 4),
    ("S8",  "Tue", 12,   15, 4),
    ("S9",  "Tue", 15,   17, 4),
    ("S10", "Tue", 17,   19, 3),

    ("S11", "Wed", 7.25, 9,  3),
    ("S12", "Wed", 9,    12, 4),
    ("S13", "Wed", 12,   15, 4),
    ("S14", "Wed", 15,   17, 4),
    ("S15", "Wed", 17,   19, 3),

    ("S16", "Thu", 7.25, 9,  3),
    ("S17", "Thu", 9,    12, 4),
    ("S18", "Thu", 12,   15, 4),
    ("S19", "Thu", 15,   17, 4),
    ("S20", "Thu", 17,   19, 3),

    ("S21", "Fri", 7.25, 9,  3),
    ("S22", "Fri", 9,    12, 4),
    ("S23", "Fri", 12,   15, 4),
    ("S24", "Fri", 15,   17, 4),

    ("S25", "Sat", 10,   14, 2),
    ("S26", "Sun", 10,   14, 2),
]

"""##How many shifts can each work"""

for i in students:
    available = sum(availability_matrix[i][(day, start, end)] for _, day, start, end, _ in shifts)
    print(f"{i} can work {available} shifts")

"""#The solution (incomplete)"""

max_weekly_hours = 20

# --- Model Setup ---
model = cp_model.CpModel()

# Create decision variables: x[s, i] = 1 if student i works shift s
x = {}
for sid, day, start, end, _ in shifts:
    for i in students:
        # Using shift_id (day, start, end) as the key for consistency with availability_matrix
        shift_id = (day, start, end)
        x[shift_id, i] = model.NewBoolVar(f"x_{sid}_{i}")

# --- 1. Shift Coverage Constraint ---
for sid, day, start, end, required in shifts:
    shift_id = (day, start, end)
    model.Add(sum(x[shift_id, i] for i in students) == required)

# --- 2. Availability Constraint ---
for sid, day, start, end, _ in shifts:
    shift_id = (day, start, end)
    for i in students:
        # Correctly use the availability_matrix to check if a student is available for this specific shift slot
        if availability_matrix.get(i, {}).get(shift_id, 0) == 0:
             model.Add(x[shift_id, i] == 0)


# --- 3. Weekly Hour Limit Constraint ---
# Need to define shift_lengths using shift_id for consistency
shift_lengths = {(day, start, end): end - start for _, day, start, end, _ in shifts}

SCALE = 4  # Scale factor to convert hours to integers

for i in students:
    total_hours_scaled = sum(x[shift_id, i] * int(shift_lengths[shift_id] * SCALE) for shift_id in shift_lengths)
    model.Add(total_hours_scaled <= max_weekly_hours * SCALE)


# --- 4. Fairness Objective: Minimize (max - min) total hours ---
total_hours = {i: model.NewIntVar(0, max_weekly_hours * SCALE, f"total_hours_{i}") for i in students} # Scale the bounds
for i in students:
    # Calculate scaled total hours for each student
    model.Add(total_hours[i] == sum(x[shift_id, i] * int(shift_lengths[shift_id] * SCALE) for shift_id in shift_lengths))


max_hours_scaled = model.NewIntVar(0, max_weekly_hours * SCALE, "max_hours_scaled") # Scale the bounds
min_hours_scaled = model.NewIntVar(0, max_weekly_hours * SCALE, "min_hours_scaled") # Scale the bounds
model.AddMaxEquality(max_hours_scaled, list(total_hours.values()))
model.AddMinEquality(min_hours_scaled, list(total_hours.values()))

model.Minimize(max_hours_scaled - min_hours_scaled)

# --- Solve ---
solver = cp_model.CpSolver()
status = solver.Solve(model)

# --- Output ---
if status in [cp_model.OPTIMAL, cp_model.FEASIBLE]:
    print("Final Shift Assignment:")
    # Iterate through shifts to print assignments
    for sid, day, start, end, required in shifts:
        shift_id = (day, start, end)
        assigned = [i for i in students if solver.Value(x[shift_id, i])]
        print(f"  {sid} ({day} {start}:00–{end}:00): {', '.join(assigned)}")

    print("Total Assigned Hours per Student:")
    for i in students:
        # Convert scaled hours back to original hours for display
        print(f"  {i}: {solver.Value(total_hours[i]) / SCALE} hours")

else:
    print("No feasible schedule found.")
    print(f"Solution Status: {solver.StatusName(status)}")

for _, day, start, end, required in shifts:
    shift_id = (day, start, end)
    available_within_limit = 0
    for student in students:
        if availability_matrix[student][shift_id] == 1:
            # Calculate potential hours if this student takes this shift, ignoring other shifts for now
            potential_hours = (end - start)
            if potential_hours <= 20: # This is a simplified check, doesn't account for other shifts
                 available_within_limit += 1
    print(f"{day} {start}-{end}: {available_within_limit} students available and potentially within 20 hours (need {required})")

total_available_hours = 0
for student in students:
    for sid, day, start, end, _ in shifts:
        shift_id = (day, start, end)
        if availability_matrix[student][shift_id] == 1:
            total_available_hours += (end - start)

print(f"Total available hours across all students: {total_available_hours}")

total_required_hours = 0
for sid,day, start, end, required in shifts:
    total_required_hours += (end - start) * required

print(f"Total required hours for all shifts: {total_required_hours}")